### ISSUE TITLE
Several Error

### ISSUE THREAD

**Issue by Totentanz85** [seth-rah/FFXIV_Telegram_News#1]
Hey!
I love your bot, it worked amazing, but since today it stopped working. I get several Error in node.modules. 
I hope you can fix it, I can´t!

**Comment by Totentanz85** [comment]
Nvm was only lodestone Maintenance work. I'm sorry for the bother, everything is fine.

**Comment by seth-rah** [comment]
I'll have a look to see if I can make it provide more accurate logging when the site is under maintenance. 

Thanks for the feedback, I wasn't aware anyone else was actually using this.

**Comment by seth-rah** [comment]
If you could share the logs that you had during the maintenance window I'd appreciate it.
